version: '2.2'
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8000:8000
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: nginx
        restart: always
 
    node:
        depends_on:
            - reverseproxy
        image: ssabanovic/getting-started
        ports:
            - 3000:3000
        restart: always
    
    bulletin:
        depends_on:
            - reverseproxy
        image: bulletin
        ports:
            - 7000:7000
        restart: always